version: '2'
services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
    networks:
      - proxy
    depends_on:
      - web

  proxy-adm:
    image: jwilder/docker-gen
    container_name: proxy-adm
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-compose-v2.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from: 
      - nginx-proxy
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: proxy-adm
  db:
    image: mariadb:10.3
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "CHANGEME"
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
  db-creation:
    image: mariadb:10.3
    env_file: .env
    environment:
      MYSQL_HOST: "db"
    entrypoint: "sh -c"
    command: ["sleep 5 && cat /init.sql | mysql -p${MYSQL_PASSWORD} -P 3306 -h db -u${MYSQL_USER} ${MYSQL_DATABASE}"]
    volumes:
      - ./init.sql:/init.sql
    links:
      - db
    depends_on:
      - db
  web:
    build: ./web/
    image: ciberseguridadweb/web
    container_name: web-server
    env_file: .env
    environment:
      MYSQL_HOST: "db"
      MYSQL_DB: "ciberweb"
      VIRTUAL_HOST: www.testing.com.es
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: www.testing.com.es
      LETSENCRYPT_EMAIL: javi@millaguie.net
    depends_on:
      - db
    links:
      - db
    restart: always
    networks:
      - proxy

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  mariadb-data:
networks:
  proxy:
    external:
      name: proxy-net